# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_auto_20161129_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('idBoleto', models.AutoField(primary_key=True, serialize=False)),
                ('asiento1', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('a6', 'A6'), ('a7', 'A7'), ('a8', 'A8'), ('a9', 'A9'), ('b5', 'B5'), ('b6', 'B6'), ('b7', 'B7'), ('b8', 'B8'), ('b9', 'B9'), ('b10', 'B10')], max_length=3)),
                ('asiento2', models.CharField(choices=[('2016-1', '2016-1'), ('2016-2', '2016-2'), ('2016-3', '2016-3'), ('2016-4', '2016-4'), ('2016-5', '2016-5'), ('2016-6', '2016-6'), ('2016-7', '2016-7'), ('2016-8', '2016-8'), ('2016-9', '2016-9'), ('2016-10', '2016-10'), ('2016-11', '2016-11'), ('2016-12', '2016-12'), ('2016-13', '2016-13'), ('2016-14', '2016-14')], max_length=6)),
                ('asiento3', models.CharField(choices=[('e21', 'E21'), ('e22', 'E22'), ('e23', 'E23'), ('e24', 'E24'), ('e25', 'E25'), ('e26', 'E26'), ('e27', 'E27'), ('e28', 'E28'), ('e29', 'E29'), ('k01', 'K01'), ('k02', 'K02'), ('k03', 'K03'), ('k04', 'K04'), ('k05', 'K05')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleto.Boleto')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
    ]
