# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCliente',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
